export enum Technology {
  React = 'React',
  Vue = 'Vue',
  Next = 'Next',
  TailwindCSS = 'TailwindCSS',
  SCSS = 'SCSS',
  Node = 'Node',
  Adonis = 'Adonis',
  Express = 'Express',
  PHP = 'PHP',
  Serverless = 'Serverless',
  PostgreSQL = 'PostgreSQL',
  MySQL = 'MySQL',
  Docker = 'Docker',
  Figma = 'Figma',
  UIUXDesign = 'UI/UX Design',
  Prototyping = 'Prototyping',
  DesignSystems = 'Design Systems',
  Agile = 'Agile',
  Git = 'Git',
  CI_CD = 'CI/CD',
  Testing = 'Testing',
  CSharp = 'C#',
  DotNet = '.NET',
  AspNet = 'ASP.NET',
  MAUI = 'MAUI',
}
